from llm_adapter import call_llm
from schema_loader import load_schema
from prompt_builder import build_prompt
from sql_guard import is_safe_sql
from query_executor import execute_sql

# 1. User question
question = "Show average GPA by department"

# 2. Load real database schema
schema = load_schema()
print("=== DATABASE SCHEMA ===")
print(schema)

# 3. Build strict SQL prompt
prompt = build_prompt(question, schema)
print("\n=== PROMPT SENT TO LLM ===")
print(prompt)

# 4. Call LLM (this fills SQL QUERY)
sql = call_llm(prompt).strip()
print("\n=== SQL GENERATED BY LLM ===")
print(sql)

# 5. Safety check
if not is_safe_sql(sql):
    raise Exception("Unsafe SQL generated by LLM")

# 6. Execute SQL
rows, columns = execute_sql(sql)

print("\n=== QUERY RESULT ===")
print(columns)
for row in rows:
    print(row)
